services:
  app:
    build: .
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./service-account.json:/app/service-account.json
      - ./data:/app/data
